"""
config.py — Unified Institutional Configuration
===============================================
Single source of truth for strategy, execution, risk, data, and reporting.

Important unit contracts:
- RISK_PER_TRADE is a fraction of available balance, not a percent.
- Strategy-layer quantity is BTC exposure.
- Delta adapter is the only layer that converts BTC <-> integer contracts.
"""

from __future__ import annotations
import os
try:
    from dotenv import load_dotenv
except ImportError:  # optional in hardened/test environments
    def load_dotenv(*args, **kwargs):
        return False

load_dotenv()

# Exchange routing
EXECUTION_EXCHANGE = os.getenv("EXECUTION_EXCHANGE", "delta").lower()

# Credentials
DELTA_API_KEY             = os.getenv("DELTA_API_KEY", "")
DELTA_SECRET_KEY          = os.getenv("DELTA_SECRET_KEY", "")
DELTA_TESTNET             = os.getenv("DELTA_TESTNET", "false").lower() == "true"
COINSWITCH_API_KEY        = os.getenv("COINSWITCH_API_KEY", "")
COINSWITCH_SECRET_KEY     = os.getenv("COINSWITCH_SECRET_KEY", "")
TELEGRAM_BOT_TOKEN        = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID          = os.getenv("TELEGRAM_CHAT_ID", "")

# Symbols / leverage / units
SYMBOL                   = "BTCUSDT"
EXCHANGE                 = "EXCHANGE_2"
LEVERAGE                 = 40
DELTA_SYMBOL             = "BTCUSD"
DELTA_CONTRACT_VALUE_BTC = 0.001
DELTA_BALANCE_CURRENCY   = "USD"
COINSWITCH_SYMBOL        = "BTCUSDT"
COINSWITCH_EXCHANGE      = "EXCHANGE_2"

# Position sizing
BALANCE_USAGE_PERCENTAGE = 60
MIN_MARGIN_PER_TRADE     = 1
MAX_MARGIN_PER_TRADE     = 10_000
MIN_POSITION_SIZE        = 0.001
MAX_POSITION_SIZE        = 1.0
LOT_STEP_SIZE            = 0.001
REMAINDER_MIN_QTY        = 0.001

# Risk management
RISK_PER_TRADE           = 0.005
MAX_DAILY_LOSS           = 10000
MAX_DAILY_LOSS_PCT       = 3.0
MAX_DRAWDOWN_PCT         = 15.0
MAX_CONSECUTIVE_LOSSES   = 2
MAX_DAILY_TRADES         = 10
ONE_POSITION_AT_A_TIME   = True
MIN_TIME_BETWEEN_TRADES  = 5.0
MIN_TIME_BETWEEN_TRADES_SEC = 300.0
TRADE_COOLDOWN_SECONDS   = 300
MIN_RISK_REWARD_RATIO    = 2.0
TARGET_RISK_REWARD_RATIO = 3.0
MAX_RR_RATIO             = 20.0
CONSEC_LOSS_AUTO_RESET_HOURS = 2.0

# Execution
TICK_SIZE_DELTA                  = 0.5
TICK_SIZE_COINSWITCH             = 0.1
TICK_SIZE                        = TICK_SIZE_DELTA if EXECUTION_EXCHANGE == "delta" else TICK_SIZE_COINSWITCH
LIMIT_ORDER_OFFSET_TICKS         = 3
ORDER_TIMEOUT_SECONDS            = 600
MAX_ORDER_RETRIES                = 2
MAX_CONSECUTIVE_TIMEOUTS         = 2
TIMEOUT_EXTENDED_LOCKOUT_SEC     = 1800
SNIPER_MAX_DISTANCE_ATR          = 1.0
LIMIT_ORDER_FILL_TIMEOUT_SEC     = 60.0
REQUEST_TIMEOUT                  = 30
GLOBAL_API_MIN_INTERVAL          = 3.0
DELTA_API_MIN_INTERVAL           = 0.25
RATE_LIMIT_ORDERS                = 15

# Data readiness
READY_TIMEOUT_SEC    = 120.0
MIN_CANDLES_1M       = 100
MIN_CANDLES_5M       = 100
MIN_CANDLES_15M      = 100
MIN_CANDLES_1H       = 20
MIN_CANDLES_4H       = 40
MIN_CANDLES_1D       = 7
LOOKBACK_CANDLES_1M  = 300
LOOKBACK_CANDLES_5M  = 2100
LOOKBACK_CANDLES_15M = 700
LOOKBACK_CANDLES_1H  = 200
LOOKBACK_CANDLES_4H  = 50
LOOKBACK_CANDLES_1D  = 30
CANDLE_TIMEFRAMES    = ["1m", "5m", "15m", "1h", "4h", "1d"]
PRIMARY_TIMEFRAME    = "15m"
ENTRY_TIMEFRAME      = "5m"
HTF_TIMEFRAME        = "4h"

# Health
WS_STALE_SECONDS                   = 35.0
HEALTH_CHECK_INTERVAL_SEC          = 12.0
PRICE_STALE_SECONDS                = 90.0
BALANCE_CACHE_TTL_SEC              = 35.0
BALANCE_FETCH_LOCK_TIMEOUT_SEC     = 45.0
STRUCTURE_UPDATE_INTERVAL_SECONDS  = 30
ENTRY_EVALUATION_INTERVAL_SECONDS  = 0.5
ENTRY_PENDING_TIMEOUT_SECONDS      = ORDER_TIMEOUT_SECONDS

# Reporting
LOG_LEVEL                    = "INFO"
TELEGRAM_REPORT_INTERVAL_SEC = 900
OUTLOOK_INTERVAL_SECONDS     = 900

# Fees
COMMISSION_RATE              = 0.00055
COMMISSION_RATE_MAKER        = 0.00020
DELTA_COMMISSION_RATE        = 0.00050
DELTA_COMMISSION_RATE_MAKER  = -0.00020
STOP_EXIT_COMMISSION_RATE    = 0.00055

# Aggregator
AGG_PRIMARY_WEIGHT   = 0.55
AGG_SECONDARY_WEIGHT = 0.45
AGG_OB_DEPTH_LEVELS  = 10
AGG_TRADE_WINDOW_SEC = 30.0

# SL/TP and ATR
SL_LIMIT_OFFSET_TICKS          = 20
SL_BUFFER_TICKS                = 5
SL_MIN_ATR_MULT                = 0.20
SL_SWEEP_WICK_CLEARANCE_MULT   = 0.10
SL_REGIME_BUFF_SLOPE           = 0.80
SL_MIN_IMPROVEMENT_PCT         = 0.001
SL_RATCHET_ONLY                = True
SL_ATR_PERIOD                  = 14
SL_ATR_BUFFER_MULT             = 0.75
SL_MIN_CLEARANCE_ATR_MULT      = 1.5
SL_MIN_IMPROVEMENT_ATR_MULT    = 0.20
TRAILING_SL_CHECK_INTERVAL     = 10
TRAIL_SWING_MAX_AGE_MS         = 14_400_000
ATR_SEED_RETAIN                = 1
ATR_PCTILE_RANK_WINDOW         = 30

# Quant strategy
QUANT_MARGIN_PCT               = 0.20
QUANT_SLIPPAGE_TOLERANCE       = 0.0005
QUANT_VWAP_ENTRY_ATR_MULT      = 1.2
QUANT_CVD_DIVERGENCE_MIN       = 0.15
QUANT_OB_CONFIRM_MIN           = 0.10
QUANT_COMPOSITE_ENTRY_MIN      = 0.35
QUANT_EXIT_REVERSAL_THRESH     = 0.40
QUANT_CONFIRM_TICKS            = 2
QUANT_SL_SWING_LOOKBACK        = 12
QUANT_SL_BUFFER_ATR_MULT       = 0.4
QUANT_TP_VWAP_FRACTION         = 0.65
QUANT_VP_BUCKET_COUNT          = 50
QUANT_VP_HVN_THRESHOLD         = 0.70
QUANT_OB_WALL_DEPTH            = 20
QUANT_OB_WALL_MULT             = 2.5
QUANT_TRAIL_SWING_BARS         = 5
QUANT_TRAIL_VOL_DECAY_MULT     = 0.6
QUANT_TRAIL_ENABLED            = True
QUANT_TRAIL_BE_R               = 1.00
QUANT_TRAIL_LOCK_R             = 1.00
QUANT_TRAIL_AGGRESSIVE_R       = 3.50
QUANT_TRAIL_LIQ_MIN_BREATHING_ATR = 1.00
QUANT_TRAIL_MIN_DIST_ATR_P1    = 2.00
QUANT_TRAIL_MIN_DIST_ATR_P2    = 1.50
QUANT_TRAIL_MIN_DIST_ATR_P3    = 1.00
QUANT_TRAIL_PULLBACK_FREEZE    = True
QUANT_TRAIL_PB_VOL_RATIO       = 0.65
QUANT_TRAIL_PB_DEPTH_ATR       = 1.20
QUANT_TRAIL_REV_MIN_SIGNALS    = 2
QUANT_ICT_ZONE_FREEZE_ENABLED  = True
QUANT_ICT_ZONE_FREEZE_ATR      = 0.40
QUANT_ICT_OB_SL_ANCHOR         = True
QUANT_ICT_OB_SL_BUFFER_ATR     = 0.35
QUANT_ICT_LIQ_CEILING_ENABLED  = True
QUANT_ICT_LIQ_POOL_BUFFER_ATR  = 0.50
QUANT_CVD_WINDOW               = 20
QUANT_CVD_HIST_MULT            = 15
QUANT_VWAP_WINDOW              = 50
QUANT_EMA_FAST                 = 8
QUANT_EMA_SLOW                 = 21
QUANT_VOL_FLOW_WINDOW          = 10
QUANT_ATR_PCTILE_WINDOW        = 100
QUANT_ATR_MIN_PCTILE           = 0.05
QUANT_ATR_MAX_PCTILE           = 0.97
QUANT_MAX_HOLD_SEC             = 3600
QUANT_COOLDOWN_SEC             = 300
QUANT_LOSS_LOCKOUT_SEC         = 1800
QUANT_POS_SYNC_SEC             = 30
RECONCILE_POST_EXIT_SETTLE_SEC = 15.0
QUANT_W_VWAP_DEV               = 0.30
QUANT_W_CVD_DIV                = 0.25
QUANT_W_OB                     = 0.20
QUANT_W_TICK_FLOW              = 0.15
QUANT_W_VOL_EXHAUSTION         = 0.10
QUANT_HTF_ENABLED              = True
QUANT_HTF_VETO_STRENGTH        = 0.70
QUANT_OB_DEPTH_LEVELS          = 5
QUANT_OB_HIST_LEN              = 60
QUANT_TICK_AGG_WINDOW_SEC      = 30.0
QUANT_TP_MAX_RR                = 3.5
QUANT_SL_SWING_DENSITY_WINDOW  = 0.30
QUANT_TRAIL_CHANDELIER_N_START = 3.00
QUANT_TRAIL_CHANDELIER_N_END   = 1.50
QUANT_TRAIL_HVN_SNAP_THRESH    = 0.55
QUANT_ADX_PERIOD               = 14
QUANT_ADX_TREND_THRESH         = 25.0
QUANT_ADX_RANGE_THRESH         = 20.0
QUANT_ATR_EXPANSION_THRESH     = 1.30
QUANT_TREND_PULLBACK_ATR_MIN   = 0.10
QUANT_TREND_PULLBACK_ATR_MAX   = 2.00
QUANT_TREND_CVD_MIN            = -0.20
QUANT_TREND_TP_ATR_MULT        = 2.5
QUANT_TREND_COMPOSITE_MIN      = 0.35
QUANT_TREND_CONFIRM_TICKS      = 3
QUANT_TREND_CHANDELIER_N       = 1.5
QUANT_MAX_SPREAD_ATR_RATIO     = 0.50
QUANT_REVERSION_MIN_RR         = 2.0
QUANT_REVERSION_MAX_RR         = 5.0
QUANT_TREND_MIN_RR             = 2.0
QUANT_TREND_MAX_RR             = 5.0
QUANT_TREND_SL_ATR_MULT        = 2.0
QUANT_TP_MIN_ATR_MULT          = 0.5
QUANT_TP_MAX_ATR_MULT          = 6.0
QUANT_REVERSION_REJECT_RR      = 0.20
QUANT_SMART_MAX_HOLD           = True
QUANT_MAX_HOLD_PROFIT_SL_ATR   = 0.5
QUANT_MAX_HOLD_EXTENSIONS      = 5
QUANT_HOLD_EXTENSION_SEC       = 1200
QUANT_THESIS_MAX_DRAWDOWN_PCT  = 0.70
QUANT_MIN_RAW_COMPOSITE        = 0.35
QUANT_MIN_CONFIRMING           = 3
QUANT_CHOCH_EXPIRY_BARS        = 10

# Fee engine
FEE_SPREAD_HIST_MAXLEN      = 500
FEE_SPREAD_DEFAULT_BPS      = 0.20
FEE_SLIP_ALPHA              = 0.25
FEE_SLIP_DEFAULT_BPS        = 1.5
FEE_SLIP_MIN_BPS            = 0.5
FEE_FLOOR_MULT_LOW          = 2.5
FEE_FLOOR_MULT_HIGH         = 1.2
FEE_FLOOR_MAX_ATR_MULT      = 2.0
FEE_FLOOR_INFLECT           = 0.45
FEE_FLOOR_STEEPNESS         = 6.0
FEE_FLOOR_ABS_MIN_MULT      = 1.2
FEE_SPREAD_ATR_WARN         = 0.06
FEE_SPREAD_PENALTY_K        = 4.0
FEE_CONF_NEUTRAL            = 0.5
FEE_CONF_MAX_DISCOUNT       = 0.30
FEE_MAKER_MIN_SAVING_BPS    = 0.5
FEE_MAKER_URGENCY_CUTOFF    = 0.82
FEE_MAKER_DEPTH_LEVELS      = 5
FEE_MAKER_DEPTH_MAX_FRAC    = 0.25
FEE_MAKER_DEPTH_FILL_FLOOR  = 0.35
FEE_MAKER_OPP_COST_WEIGHT   = 0.5

# ICT/SMC
OB_MIN_IMPULSE_PCT          = 0.15
OB_MIN_BODY_RATIO           = 0.40
OB_IMPULSE_SIZE_MULTIPLIER  = 1.30
OB_MAX_AGE_MINUTES          = 1440
FVG_MIN_SIZE_PCT            = 0.020
FVG_MAX_AGE_MINUTES         = 1440
LIQ_TOUCH_TOLERANCE_PCT     = 0.20
SWEEP_DISPLACEMENT_MIN      = 0.40
SWEEP_MAX_AGE_MINUTES       = 120
KZ_ASIA_NY_START            = 20
KZ_ASIA_NY_END              = 1
KZ_LONDON_NY_START          = 2
KZ_LONDON_NY_END            = 5
KZ_NY_NY_START              = 7
KZ_NY_NY_END                = 10
ICT_MIN_SCORE_FOR_ENTRY     = 0.25
ICT_OB_MIN_SCORE_FOR_ENTRY  = 0.20
ICT_REQUIRE_OB_OR_FVG       = False
ICT_OB_PROXIMITY_ATR        = 1.5
ICT_FVG_PROXIMITY_ATR       = 0.8
ICT_SWEEP_DISP_BONUS        = 0.12
QUANT_HTF_15M_VETO          = 0.35
QUANT_HTF_BOTH_VETO         = 0.20

# Conviction / safety
CONVICTION_MIN_SCORE               = 0.74
CONVICTION_POOL_MIN_TF_RANK        = 3
CONVICTION_DISPLACEMENT_BODY_ATR   = 0.85
CONVICTION_OTE_FIB_LOW             = 0.500
CONVICTION_OTE_FIB_HIGH            = 0.786
CONVICTION_MIN_RR                  = 2.0
CONVICTION_PRODUCT_MIN_CORE        = 0.68
CONVICTION_MAX_SESSION_LOSSES      = 2
CONVICTION_MIN_ENTRY_INTERVAL_SEC  = 420
CONVICTION_MAX_ENTRIES_PER_SESSION = 3

# Entry gates
ENTRY_HARD_MIN_DISPLACEMENT_ATR          = 0.75
ENTRY_STRONG_DISPLACEMENT_ATR            = 1.25
ENTRY_REQUIRE_CISD_OR_OTE                = True
ENTRY_MAX_CHASE_ATR_WITHOUT_OTE          = 1.15
ENTRY_REVERSAL_PD_LONG_MAX               = 0.62
ENTRY_REVERSAL_PD_SHORT_MIN              = 0.38
ENTRY_CONTINUATION_MIN_ACCEPTANCE_ATR    = 0.55
ENTRY_CONTINUATION_REQUIRE_CISD_OR_BOS   = True
ENTRY_FLOW_HARD_OPPOSE_THRESHOLD         = 0.40
ENTRY_CVD_HARD_OPPOSE_THRESHOLD          = 0.30
ENTRY_HTF_CONTRA_MAX_WITHOUT_STRONG_DISP = True
ENTRY_GATE_LOG_INTERVAL_SEC              = 12.0
ENTRY_TP_RR_SAFETY_BUFFER                = 0.05
ENTRY_TP_RR_TOLERANCE                    = 0.03
ENTRY_TP_MIN_NET_ATR                     = 0.20

# Post exit gate
POST_EXIT_BASE_SEC                 = 60.0
POST_EXIT_LOSS_DECAY_FACTOR        = 2.0
POST_EXIT_LOSS_DECAY_CAP_SEC       = 900.0
POST_EXIT_FLIP_BASE_SEC            = 120.0
POST_EXIT_FLIP_MIN_ATR_FROM_EXIT   = 1.5
POST_EXIT_FLIP_REQUIRES_BOS        = True
POST_EXIT_TP_SAMESIDE_BASE_SEC     = 90.0
POST_EXIT_TP_SAMESIDE_PULLBACK_PCT = 0.50
POST_EXIT_ATR_SHOCK_PCT            = 0.40
POST_EXIT_ATR_SHOCK_PENALTY_SEC    = 180.0
POST_EXIT_STRUCTURE_PROOF_REQUIRED = True
POST_EXIT_STRUCTURE_PROOF_TIMEOUT  = 240.0
POST_EXIT_LOSS_SAMESIDE_DEAD_SEC   = 300.0

# Liquidity trail / profit defense
QUANT_TRAIL_LIQ_BASE_BUF_MAX_ATR  = 0.25
QUANT_TRAIL_LIQ_BASE_BUF_MIN_ATR  = 0.15
QUANT_TRAIL_LIQ_SAFETY_BUF_ATR    = 0.28
QUANT_TRAIL_LIQ_POOL_LOOKBACK_ATR = 8.0
QUANT_TRAIL_LIQ_BOS_CONFIRM_GATE  = True
QUANT_TRAIL_LIQ_BOS_MAX_AGE_MS    = 10_000_000
QUANT_TRAIL_DISP_CVD_GATE         = True
QUANT_TRAIL_CVD_MIN_TREND         = 0.12
QUANT_TRAIL_DISP_MIN_ATR_MULT     = 0.58
QUANT_TRAIL_DISP_CVD_MIN_R        = 0.30
QUANT_TRAIL_OB_BREAKER_PRIORITY   = True
QUANT_TRAIL_OB_BREAKER_BUFFER_ATR = 0.22
QUANT_TRAIL_AMD_MANIP_BUFFER_MULT = 1.55
QUANT_TRAIL_AMD_DIST_BUFFER_MULT  = 0.62
QUANT_TRAIL_AMD_REDIST_BUFFER_MULT = 1.12
QUANT_TRAIL_HTF_CASCADE_ENABLED   = True
QUANT_TRAIL_LIQ_POOL_PROX_ATR     = 2.20
QUANT_TRAIL_LIQ_FLOOR_BUFFER_ATR  = 0.30
PROFIT_DEFENSE_MIN_MFE_ATR        = 1.80
PROFIT_DEFENSE_GIVEBACK_FRAC      = 0.72
PROFIT_DEFENSE_COUNTER_CVD        = 0.30
PROFIT_DEFENSE_BOS_MAX_AGE_MS     = 720_000
PROFIT_DEFENSE_BE_CUSHION_ATR     = 0.05
PROFIT_DEFENSE_MIN_INTERVAL_SEC   = 90.0
PROFIT_DEFENSE_POOL_GATE_MAX_AGE_SEC = 180.0
PROFIT_DEFENSE_FAILED_DELIVERY_MIN_MFE_ATR = 2.50
PROFIT_DEFENSE_FAILED_DELIVERY_GIVEBACK_FRAC = 0.78
PROFIT_DEFENSE_MIN_NET_ATR_TO_EXIT = 0.35
PROFIT_DEFENSE_ALLOW_GIVEBACK_ONLY_EXIT = False
TRAIL_BE_MIN_BREATHING_ATR = 0.75
TRAIL_PHASE0_MAX_DELIVERY_ATR = 0.75
TRAIL_STRUCTURE_MIN_DELIVERY_ATR = 1.10
TRAIL_AGGRESSIVE_MIN_DELIVERY_ATR = 2.60
TRAIL_DELIVERY_LOCK_MIN_MFE_ATR = 1.80
TRAIL_DELIVERY_POOL_MIN_SIG = 3.0
TRAIL_DELIVERY_POOL_BUFFER_ATR = 0.30
TRAIL_DELIVERY_SWING_BUFFER_ATR = 0.30
TRAIL_DELIVERY_SWING_LOOKBACK_BARS = 36
TRAIL_DELIVERY_LOCK_MIN_BREATHING_ATR = 0.85
TRAIL_DELIVERY_LOCK_MIN_IMPROVEMENT_ATR = 0.25
EXIT_MANUAL_CONFIRM_MAX_WAIT_SEC = 120.0

# Market intelligence
MI_COMPRESSED_ATR_PCT = 0.08
MI_EXPANDED_ATR_PCT   = 0.28
MI_STRESS_ATR_PCT     = 0.55
MI_LIQ_DENSITY_RADIUS_ATR = 4.0
MI_WIDE_SPREAD_BPS = 5.0
MI_ENABLE_DYNAMIC_ENTRY_GATES = True
MI_ENABLE_DYNAMIC_CONVICTION_GATES = True
MI_ENABLE_DYNAMIC_TRAILING_GATES = True
MI_ENABLE_DYNAMIC_POST_EXIT_GATES = True

SESSION_TRAIL_WIDTH_MULT = {
    "asia": 1.60, "london": 1.20, "ny": 1.00, "late_ny": 1.30, "off": 1.50,
}
SESSION_ENTRY_QUALITY = {
    "asia": "LOW", "london": "HIGH", "ny": "HIGH", "late_ny": "MEDIUM", "off": "LOW",
}


def get_tick_size(exchange: str | None = None) -> float:
    ex = (exchange or EXECUTION_EXCHANGE or "").lower()
    if ex == "delta":
        return float(TICK_SIZE_DELTA)
    if ex == "coinswitch":
        return float(TICK_SIZE_COINSWITCH)
    return float(TICK_SIZE)


def validate_config() -> None:
    errors: list[str] = []
    if not (0.0 < RISK_PER_TRADE <= 0.05):
        errors.append("RISK_PER_TRADE must be a fraction in (0, 0.05]")
    if MIN_RISK_REWARD_RATIO < 1.5:
        errors.append("MIN_RISK_REWARD_RATIO must be >= 1.5")
    if abs(CONVICTION_MIN_RR - MIN_RISK_REWARD_RATIO) > 1e-9:
        errors.append("CONVICTION_MIN_RR must match MIN_RISK_REWARD_RATIO")
    if abs(QUANT_REVERSION_MIN_RR - MIN_RISK_REWARD_RATIO) > 1e-9:
        errors.append("QUANT_REVERSION_MIN_RR must match MIN_RISK_REWARD_RATIO")
    if TARGET_RISK_REWARD_RATIO < MIN_RISK_REWARD_RATIO:
        errors.append("TARGET_RISK_REWARD_RATIO must be >= MIN_RISK_REWARD_RATIO")
    if get_tick_size() <= 0:
        errors.append("tick size must be positive")
    if MAX_DAILY_LOSS_PCT <= 0 or MAX_DAILY_LOSS_PCT > 10:
        errors.append("MAX_DAILY_LOSS_PCT must be in (0, 10]")
    if RISK_PER_TRADE * MAX_CONSECUTIVE_LOSSES > (MAX_DAILY_LOSS_PCT / 100.0) + 1e-12:
        errors.append("consecutive-loss risk budget exceeds daily-loss budget")
    if errors:
        raise ValueError("Invalid config: " + "; ".join(errors))


validate_config()
