"""
config.py

Institutional v53 configuration.
This file contains safety rails only. It does not create fallback levels or synthetic data.
"""

SYMBOL = "BTCUSD"
EXCHANGE = "delta"
LEVERAGE = 40

# Tick / exchange constraints
TICK_SIZE = 0.1
MIN_QTY = 0.001
QTY_STEP = 0.001
MIN_NOTIONAL = 5.0
CONTRACT_VALUE = 1.0

# Risk
RISK_PER_TRADE_PCT = 0.0035
MAX_MARGIN_USAGE_PCT = 0.20
MAX_DAILY_LOSS_PCT = 0.025
MAX_CONSECUTIVE_LOSSES = 3

# Entry lifecycle
MIN_RISK_REWARD_RATIO = 1.8
ENTRY_MIN_TARGET_PROBABILITY = 0.18
ENTRY_MIN_NET_EV_R = 0.05
ENTRY_MIN_ROUTE_UTILITY = 0.0
ENTRY_MIN_RISK_ATR = 0.45
ENTRY_MAX_RISK_ATR = 3.50
ENTRY_ROUND_TRIP_FEE_RATE = 0.00110
ENTRY_SLIPPAGE_ATR = 0.03

# Sweep / entry proof
ENTRY_MIN_SWEEP_QUALITY = 0.52
ENTRY_MIN_CONVICTION = 0.55
ENTRY_REQUIRE_CISD_OR_OTE = True
ENTRY_ALLOW_DISPLACEMENT_WITHOUT_OTE = False
ENTRY_MAX_CHASE_ATR_WITHOUT_OTE = 1.15
ENTRY_SL_BUFFER_ATR = 0.12
ENTRY_NOISE_FLOOR_ATR = 0.45

# Refined entry
ENTRY_REFINE_TTL_SEC = 900
ENTRY_REFINE_MIN_RETRY_SEC = 8
ENTRY_REFINE_MAX_ATTEMPTS = 18
ENTRY_REFINE_MIN_PULLBACK_ATR = 0.25
ENTRY_REFINE_MIN_DELIVERY_ATR = 0.35
ENTRY_REFINE_MIN_RISK_COMPRESSION = 0.18

# Exit
TRAIL_BE_MIN_R = 0.85
TRAIL_STRUCTURE_LOCK_MIN_R = 1.20
TRAIL_ATR_NOISE_BUFFER = 0.18
TRAIL_REQUIRE_STRUCTURE_CONFIRMATION = True
