import inspect

from strategy.liquidity_trail import LiquidityTrailEngine
from strategy.quant_strategy import QuantStrategy


def test_v76_runtime_fingerprint_present():
    src = inspect.getsource(QuantStrategy._log_init)
    assert "v76-trail-safe-margin-true-flow" in src
    assert "v74-native-bracket-fast-fee-true-flow" not in src
    assert "v70-flow-audit" not in src


def test_v76_delivery_lock_receives_computed_r_multiple():
    sig = inspect.signature(LiquidityTrailEngine._try_delivery_structure_lock)
    assert "r_multiple" in sig.parameters
    src = inspect.getsource(LiquidityTrailEngine.compute)
    assert "hold_reason, r_multiple=r_multiple" in src
    lock_src = inspect.getsource(LiquidityTrailEngine._try_delivery_structure_lock)
    assert 'phase="DELIVERY_LOCK", r_multiple=r_multiple' in lock_src
    assert 'phase="DELIVERY_LOCK", r_multiple=0.0' not in lock_src


def test_v76_counter_bos_does_not_emit_non_executable_be_stop():
    src = inspect.getsource(LiquidityTrailEngine.compute)
    assert "COUNTER_BOS_BE_NOT_EXECUTABLE" in src
    assert "_stop_trigger_invalid_reason(pos_side, rounded_be, price)" in src
    assert "No REST retry" not in src  # dispatch-layer warning should not be generated by trail proposal
