let STATE={assets:[],positions:[],alerts:[],events:[],charts:{price:{},spread:{},r:{},pnl:[]},system:{}};
const $=id=>document.getElementById(id);const money=v=>`${v>=0?'+':''}$${Number(v||0).toFixed(2)}`;const price=v=>`$${Number(v||0).toFixed(Number(v||0)>100?2:4)}`;const ts=v=>v?new Date(v*1000).toLocaleTimeString():'--';
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});
function metric(label,val,cls=''){return `<div class="metric"><span>${label}</span><b class="${cls}">${val}</b></div>`}
function render(){const s=STATE.system||{};$('status').textContent=s.bot_online?'BOT ONLINE':'BOT OFFLINE';$('status').className=`pill ${s.bot_online?'ok':'bad'}`;$('clock').textContent=new Date().toLocaleTimeString();$('summary').innerHTML=[metric('Assets',s.assets||0),metric('Open Positions',s.open_positions||0),metric('Live UPNL',money(s.total_upnl||0),(s.total_upnl||0)>=0?'ok':'bad'),metric('Realized',money(s.total_realized||0),(s.total_realized||0)>=0?'ok':'bad'),metric('Source',s.source||'--'),metric('Heartbeat',ts(s.last_heartbeat))].join('');renderAssets();renderPositions();renderAlerts();renderEvents();drawAll();}
function assetCard(a){const phase=(a.phase||a.state||'').toUpperCase();let cls=phase.includes('DEFER')?'warn':phase.includes('ACTIVE')?'ok':phase.includes('ERROR')?'bad':'blue';return `<div class="card"><div class="row"><h3>${a.asset}</h3><span class="badge">${a.venue||a.primary}:${a.symbol||''}</span></div><div class="row"><span class="muted">State</span><b class="${cls}">${phase}</b></div><div class="row"><span class="muted">Price</span><b>${price(a.price)}</b></div><div class="row"><span class="muted">Direction</span><b>${a.direction||'--'} ${Number(a.confidence||0).toFixed(2)}</b></div><div class="row"><span class="muted">Spread</span><b>${Number(a.spread_bps||0).toFixed(2)} bps</b></div><div class="row"><span class="muted">ATR</span><b>${Number(a.atr||0).toFixed(4)}</b></div><div class="row"><span class="muted">Size mult</span><b>${Number(a.size_mult||1).toFixed(2)}</b></div><div class="muted">${a.last_reason||''}</div></div>`}
function renderAssets(){const q=($('assetFilter')?.value||'').toLowerCase();const arr=(STATE.assets||[]).filter(a=>(a.asset+a.symbol+a.venue).toLowerCase().includes(q));$('assetGrid').innerHTML=arr.map(assetCard).join('')||'<div class="card muted">No assets yet</div>';$('heatmap').innerHTML=(STATE.assets||[]).map(a=>`<div class="tile"><b>${a.asset}</b><div>${price(a.price)}</div><div class="muted">${a.phase||a.state}</div><div class="${(a.spread_bps||0)>50?'warn':'ok'}">${Number(a.spread_bps||0).toFixed(1)} bps</div></div>`).join('')}
function posCard(p){return `<div class="card"><div class="row"><h3>${p.asset}</h3><span class="badge">${p.venue}:${p.symbol}</span></div><div class="row"><span>${p.side} · ${p.state} · trail ${p.trailing}</span><b class="${p.upnl>=0?'ok':'bad'}">${money(p.upnl)}</b></div><div class="row"><span class="muted">Entry</span><b>${price(p.entry)}</b></div><div class="row"><span class="muted">Mark</span><b>${price(p.price)}</b></div><div class="row"><span class="muted">SL / TP</span><b>${price(p.sl)} / ${price(p.tp)}</b></div><div class="row"><span class="muted">R / MFE</span><b>${Number(p.r||0).toFixed(2)} / ${Number(p.mfe_r||0).toFixed(2)}</b></div></div>`}
function renderPositions(){$('positionGrid').innerHTML=(STATE.positions||[]).map(posCard).join('')||'<div class="card muted">No live positions</div>'}
function renderAlerts(){$('alerts').innerHTML=(STATE.alerts||[]).slice(0,100).map(a=>`<div class="item"><div class="row"><b class="${a.severity==='critical'?'bad':'warn'}">${a.title}</b><span class="badge">${a.asset||''} ${ts(a.ts)}</span></div><div class="muted">${a.message}</div></div>`).join('')||'<div class="item muted">No alerts</div>'}
function renderEvents(){$('events').innerHTML=(STATE.events||[]).slice(0,200).map(e=>`<div class="item"><div class="row"><b class="blue">${e.type}</b><span class="badge">${e.asset||''} ${ts(e.ts)}</span></div><div class="muted">${e.last_reason||e.reason||e.message||e.title||''}</div></div>`).join('')}
function drawLine(canvas, series, key='value', color='#6aa8ff'){const c=canvas.getContext('2d'),w=canvas.width=canvas.clientWidth*2,h=canvas.height=canvas.clientHeight*2;c.clearRect(0,0,w,h);c.strokeStyle='#20304c';c.lineWidth=1;for(let i=0;i<5;i++){let y=h*i/4;c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}if(!series||series.length<2)return;const vals=series.map(x=>Number(x[key]||0));let mn=Math.min(...vals),mx=Math.max(...vals);if(mx===mn){mx+=1;mn-=1}c.strokeStyle=color;c.lineWidth=3;c.beginPath();series.forEach((p,i)=>{let x=w*i/(series.length-1),y=h-(Number(p[key]||0)-mn)/(mx-mn)*h;if(i)c.lineTo(x,y);else c.moveTo(x,y)});c.stroke()}
function drawAll(){drawLine($('pnlChart'),STATE.charts?.pnl||[],'value','#20d49b');const first=(STATE.assets||[])[0]?.asset;drawLine($('priceChart'),first?(STATE.charts.price[first]||[]):[],'value','#6aa8ff');drawLine($('spreadChart'),first?(STATE.charts.spread[first]||[]):[],'bps','#f6bd4f');drawLine($('rChart'),first?(STATE.charts.r[first]||[]):[],'r','#ff6475')}
$('assetFilter')?.addEventListener('input',renderAssets);async function refresh(){try{const r=await fetch('/api/state');STATE=await r.json();render()}catch(e){$('status').textContent='DASHBOARD ERROR';$('status').className='pill bad'}}refresh();setInterval(refresh,1500);
